# Help
[Help and Documentation in IPython](https://jakevdp.github.io/PythonDataScienceHandbook/01.01-help-and-documentation.html) 裡面提到：用 ?,??,`<Tab>` 來求助很好用。

# Python List

In [191]:
print(range(10))
L = list(range(10))
L

range(0, 10)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [192]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [193]:
L3=[float(x) for x in L2]
L3

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [194]:
L4 = [True, "2", 3.0, 4]
[type(item) for item in L4]

[bool, str, float, int]

# Python array

In [195]:
import array
L = list(range(10))
A = array.array('i', L)
print(type(A))
print(A)
A

<class 'array.array'>
array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Numpy

In [196]:
import numpy as np


## Creating Arrays from Python Lists

In [197]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [198]:
np.array([1, 2, 3, 4], dtype='float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [199]:
np.array([1, 2, 3, 4], dtype='float')

array([ 1.,  2.,  3.,  4.])

In [200]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [201]:
np.array(range(8))

array([0, 1, 2, 3, 4, 5, 6, 7])

## Creating Arrays from Scratch
[link](#NumPy-Array-Attributes)

In [202]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [203]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [204]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [205]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [206]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [207]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))


array([[ 0.44171092,  0.97958673,  0.35944446],
       [ 0.48089353,  0.68866118,  0.88047589],
       [ 0.91823547,  0.21682214,  0.56518887]])

In [208]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.02752832,  1.12060466, -0.22403878],
       [-0.42018339,  0.99982969,  0.43103415],
       [-0.65091287, -1.49874039, -1.23063497]])

In [209]:
np.random.randint(0,10,(2,3))

array([[8, 2, 3],
       [2, 0, 8]])

In [210]:
# Create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [211]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([ 1.,  1.,  1.])

In [212]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [213]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [214]:
type(np.zeros(10, dtype=np.int16)[0])

numpy.int16

## NumPy Array Attributes

In [215]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [216]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [217]:
print("dtype:", x3.dtype)
x3.dtype

dtype: int32


dtype('int32')

In [218]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


## Array Indexing: Accessing Single Elements

In [219]:
x1

array([5, 0, 3, 3, 7, 9])

In [220]:
x1[0] = 3.14159  # this will be truncated!

## Array Slicing: Accessing Subarrays

In [221]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [222]:
x[:5]

array([0, 1, 2, 3, 4])

In [223]:
x[::2]

array([0, 2, 4, 6, 8])

In [224]:
x[1::2]

array([1, 3, 5, 7, 9])

## Multi-dimensional subarrays

In [225]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [226]:
x2[:3, ::2] 

array([[3, 2],
       [7, 8],
       [1, 7]])

## Accessing array rows and columns

In [227]:
print(x2[:, 0])

[3 7 1]


In [228]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [229]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


## Creating copies of arrays

In [230]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [231]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [232]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [233]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Reshaping of Arrays

In [234]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [235]:
x = np.array([1, 2, 3])

# row vector via reshape
y=x.reshape((1, 3))
print(x)
print(y)


[1 2 3]
[[1 2 3]]


In [236]:
# row vector via newaxis
x[np.newaxis, :]


array([[1, 2, 3]])

In [237]:
x

array([1, 2, 3])

In [238]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [239]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [240]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [241]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])


array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [242]:
np.hstack([grid,[[3],[4]]])

array([[9, 8, 7, 3],
       [6, 5, 4, 4]])

In [243]:
x=[np.random.randint(3,10,3)]
for i in range(5):
    x=np.vstack([x,np.random.randint(3,10,3)])
x

array([[7, 6, 7],
       [7, 7, 3],
       [9, 7, 6],
       [5, 8, 8],
       [8, 3, 4],
       [8, 4, 6]])

In [244]:
x=np.random.randint(3,10,3)
for i in range(5):
    x=np.vstack([x,np.random.randint(3,10,3)])
x

array([[3, 8, 9],
       [3, 4, 5],
       [7, 5, 3],
       [8, 6, 5],
       [5, 8, 3],
       [8, 4, 3]])

In [245]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [246]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [247]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Exploring NumPy's UFuncs

In [248]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [249]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

2.84 s ± 38.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [250]:
timeit (1.0 / big_array)

5.32 ms ± 163 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [251]:
abs(np.array([-3,2]))

array([3, 2])

In [252]:
theta = np.linspace(0, np.pi, 3)

In [253]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [ 0.          1.57079633  3.14159265]
sin(theta) =  [  0.00000000e+00   1.00000000e+00   1.22464680e-16]
cos(theta) =  [  1.00000000e+00   6.12323400e-17  -1.00000000e+00]
tan(theta) =  [  0.00000000e+00   1.63312394e+16  -1.22464680e-16]


In [254]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [ 0.          0.0010005   0.01005017  0.10517092]
log(1 + x) = [ 0.          0.0009995   0.00995033  0.09531018]


# Scipy

In [255]:
from scipy import special

In [256]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))


gamma(x)     = [  1.00000000e+00   2.40000000e+01   3.62880000e+05]
ln|gamma(x)| = [  0.           3.17805383  12.80182748]
beta(x, 2)   = [ 0.5         0.03333333  0.00909091]


In [257]:
x = np.arange(5)
#y = np.empty(5)
y=np.empty(5,dtype=int)
z=np.empty(5)
np.multiply(x, 10, out=y)   # 可以節省記憶體
np.multiply(x, 10, out=z)   # 可以節省記憶體
print(y)
print(z)

[ 0 10 20 30 40]
[  0.  10.  20.  30.  40.]


In [258]:
x=[1, 2 ,3]
print(x)
print(np.array(x))

[1, 2, 3]
[1 2 3]


In [259]:
x = np.arange(5)
y = np.zeros(10)
np.power(2, x, out=y[::2])   # 可以節省記憶體
print(y)


[  1.   0.   2.   0.   4.   0.   8.   0.  16.   0.]


`y[::2] = 2 ** x` would have resulted in the creation of a temporary array to hold the results of `2 ** x`, followed by a second operation copying those values into the `y` array.

In [260]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [261]:
np.multiply.reduce(x)

120

In [262]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [263]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)